---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector-role

- name: Install Lighthouse
  tags: lighthouse
  hosts: lighthouse
  handlers:
    - name: Nginx reload
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Copy nginx configuration file
      become: true
      ansible.builtin.template:
        src: nginx_lighthouse.conf
        dest: "/etc/nginx/conf.d/lighthouse.conf"
        owner: "0"
        group: "0"
        mode: "0664"
      notify: Start nginx service
  roles:
    - lighthouse-role
